credit_model/urls.py
from django.contrib import admin
from django.urls import path
from credit_model.views import (landing_index,ProdModel,thanks_index,load_cities,about,FedDataView)
from django.conf.urls.static import static

app_name = 'credit_model'

urlpatterns = [
    path('',landing_index,name='landing_index'),
    path('model/',ProdModel.as_view(),name='model_input'),
    path('about/',about,name='about'),
    path('thanks/',thanks_index,name='thanks_index'),
    path('fed_data/',FedDataView.as_view(),name='fed_data'),
    path('ajax/load-cities/',load_cities, name='ajax_load_cities'),
]

credit_risk_heroku/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

app_name = 'credit_risk_heroku'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('credit_model.urls',namespace='home')),
]

credit_model/models.py
from django.db import models
from django.core.validators import MaxValueValidator,MinValueValidator
# Create your models here.

class State(models.Model):

    state_vals = (('CA', 'CA'),
                  ('WI', 'WI'),
                  ('NJ', 'NJ'),
                  ('TX', 'TX'),
                  ('LA', 'LA'),
                  ('FL', 'FL'),
                  ('AZ', 'AZ'),
                  ('MD', 'MD'),
                  ('ID', 'ID'),
                  ('MA', 'MA'),
                  ('UT', 'UT'),
                  ('NY', 'NY'),
                  ('MN', 'MN'),
                  ('WV', 'WV'),
                  ('AR', 'AR'),
                  ('IN', 'IN'),
                  ('IL', 'IL'),
                  ('GA', 'GA'),
                  ('OH', 'OH'),
                  ('NV', 'NV'),
                  ('NC', 'NC'),
                  ('MO', 'MO'),
                  ('KS', 'KS'),
                  ('VA', 'VA'),
                  ('WA', 'WA'),
                  ('TN', 'TN'),
                  ('CT', 'CT'),
                  ('CO', 'CO'),
                  ('SC', 'SC'),
                  ('RI', 'RI'),
                  ('NM', 'NM'),
                  ('IA', 'IA'),
                  ('PA', 'PA'),
                  ('MI', 'MI'),
                  ('NH', 'NH'),
                  ('ME', 'ME'),
                  ('KY', 'KY'),
                  ('DE', 'DE'),
                  ('MS', 'MS'),
                  ('WY', 'WY'),
                  ('AL', 'AL'),
                  ('VT', 'VT'),
                  ('OR', 'OR'),
                  ('OK', 'OK'),
                  ('MT', 'MT'),
                  ('HI', 'HI'),
                  ('DC', 'DC'),
                  ('NE', 'NE'),
                  ('ND', 'ND'))
    name = models.CharField(choices=sorted(state_vals),max_length=2)

    def __str__(self):
        return self.name

class City(models.Model):

    state = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=600)

    def __str__(self):
        return self.name

class Loan(models.Model):

    # rural = 2
    # urban = 1
    # undefined = 0
    # new_bus = 1
    # exiting_bus = 2

    NewExist_vals = (
         ('New Business','New Business'),
         ('Existing Business','Existing Business'))
    UrbanRural_vals = (
         ('Undefined','Undefined'),
         ('Urban','Urban'),
         ('Rural','Rural'))
    BankState_vals = (('NC', 'NC'),
                           ('IL', 'IL'),
                           ('RI', 'RI'),
                           ('TX', 'TX'),
                           ('VA', 'VA'),
                           ('WI', 'WI'),
                           ('MA', 'MA'),
                           ('UT', 'UT'),
                           ('NY', 'NY'),
                           ('CA', 'CA'),
                           ('MN', 'MN'),
                           ('WV', 'WV'),
                           ('AR', 'AR'),
                           ('MD', 'MD'),
                           ('NV', 'NV'),
                           ('MO', 'MO'),
                           ('ND', 'ND'),
                           ('KS', 'KS'),
                           ('IN', 'IN'),
                           ('OH', 'OH'),
                           ('TN', 'TN'),
                           ('LA', 'LA'),
                           ('CT', 'CT'),
                           ('AL', 'AL'),
                           ('DE', 'DE'),
                           ('WA', 'WA'),
                           ('NE', 'NE'),
                           ('CO', 'CO'),
                           ('ID', 'ID'),
                           ('PA', 'PA'),
                           ('SD', 'SD'),
                           ('DC', 'DC'),
                           ('NH', 'NH'),
                           ('GA', 'GA'),
                           ('MS', 'MS'),
                           ('FL', 'FL'),
                           ('WY', 'WY'),
                           ('IA', 'IA'),
                           ('NJ', 'NJ'),
                           ('VT', 'VT'),
                           ('OR', 'OR'),
                           ('OK', 'OK'),
                           ('AZ', 'AZ'),
                           ('SC', 'SC'),
                           ('MI', 'MI'),
                           ('HI', 'HI'),
                           ('KY', 'KY'),
                           ('NM', 'NM'))

    city = models.ForeignKey(City, on_delete=models.CASCADE)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    bank_state = models.CharField(choices=sorted(BankState_vals),max_length=2)
    term = models.PositiveIntegerField(validators=[MaxValueValidator(360)])
    number_emp = models.PositiveIntegerField(validators=[MaxValueValidator(360000)])
    new_exist = models.CharField(choices=sorted(NewExist_vals),max_length=60)
    urban_rural =  models.CharField(choices=sorted(UrbanRural_vals),max_length=60)
    disbursement_gross = models.IntegerField(validators=[MaxValueValidator(3600000)])
    prediction_prob = models.FloatField()

    def __str__(self):
        return self.id


class FedChargeOff(models.Model):
    DefaultRate = models.FloatField()
    Year = models.PositiveIntegerField(validators=[MaxValueValidator(2100)])
    Quarter = models.PositiveIntegerField(validators=[MaxValueValidator(4)])

    def __str__(self):
        return self.id

credit_model/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms.fields import DateField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from credit_model.models import Loan,City,State



class LoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ['city','state','bank_state','term','number_emp','new_exist','urban_rural','disbursement_gross']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()
        if 'city' in self.data:
            try:
                state_id = int(self.data.get('state'))
                self.fields['city'].queryset = City.objects.filter(state_id=state_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.state.city_set.order_by('name')

credit_model/views.py
from django.shortcuts import render
from django.conf import settings
from credit_model.tables import FedTable
from django.views.generic import (View,TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView,
                                  FormView)
from credit_model.forms import LoanForm
from credit_model.models import Loan,City,State,FedChargeOff
# from credit_model. import LoanForm
import pickle
import os
import pandas as pd
from django_tables2 import RequestConfig, SingleTableMixin, SingleTableView
from django_filters.views import FilterView
from credit_model.filters import FedFilter


RFM_PATH = os.path.join(settings.DS_MODELS,'RandomForestModel.sav')
PROD_TEST_ROUTE = os.path.join(settings.DS_MODELS,'production_test.csv')
PROD_TRAIN_ROUTE = os.path.join(settings.DS_MODELS,'production_train.csv')

def landing_index(request):
    return render(request,'credit_model/landing_index.html')

def thanks_index(request):
    return render(request,'credit_model/thanks.html')

def about(request):
    return render(request,'credit_model/about.html')


class FedDataView(SingleTableMixin,FilterView):
   context_object_name = 'FedData'
   model = FedChargeOff
   table_class = FedTable
   filterset_class = FedFilter
   template_name='credit_model/fed_data.html'

def RfcModel(city_val,state_val,BankState,Term,NumberEmp,NewExist,UrbanRural,DisbursementGross):
    prod_test = pd.read_csv(PROD_TEST_ROUTE) # File Route
    prod_train = pd.read_csv(PROD_TRAIN_ROUTE) # File Route
    # Gather inputs and arrange them as a single row dataframe
    row_df = pd.DataFrame([pd.Series([city_val,state_val,BankState,Term,NumberEmp,NewExist,UrbanRural,DisbursementGross],index=prod_test.columns)])
    # Add production sets to new test data
    concat_df = pd.concat([prod_train,prod_test,row_df])
    # dummie all values possible with train, test, and production data
    feature_df = pd.get_dummies(concat_df)
    # Drop target variable from dataset
    feature_df.drop(['MIS_Status'], axis=1,inplace=True)
    # Gather the now dummies production values
    x = feature_df.iloc[[-1]].copy()
    # Read in model
    randomforest = pickle.load(open(RFM_PATH,'rb'))
    # Predict probability of loan default
    prediction = randomforest.predict_proba(x)
    # Return probability of default only
    return prediction[:,1] # Gathers the probability of default

class ProdModel(FormView):
    template_name = 'credit_model/model_index.html'
    form_class = LoanForm

    def post(self, request):
        if request.method == 'POST':
            # create a form instance and populate it with data from the request:
            form = LoanForm(request.POST)
            # check whether it's valid:
            if form.is_valid():
                # Gathering cleaned values
                City = form.cleaned_data['city']
                City_val = City.name # Gathers the actual city name, not the unique ID
                State = form.cleaned_data['state']
                State_val = State.name # Gathers the actual state name, not the unique ID
                BankState = form.cleaned_data['bank_state']
                Term = form.cleaned_data['term']
                NumberEmp = form.cleaned_data['number_emp']
                NewExist = form.cleaned_data['new_exist']
                UrbanRural = form.cleaned_data['urban_rural']
                DisbursementGross = form.cleaned_data['disbursement_gross']
                # Input values into the model and return a probability of default
                loan_default_prob = RfcModel(City_val,State_val,BankState,Term,NumberEmp,NewExist,UrbanRural,DisbursementGross)
                # gather the values and their prediction value into a database
                model_insert = Loan(city=City,state=State,
                                    bank_state=BankState,
                                    term=Term,
                                    number_emp=NumberEmp,
                                    new_exist=NewExist,
                                    urban_rural=UrbanRural,
                                    disbursement_gross=DisbursementGross,
                                    prediction_prob=loan_default_prob)
                # Insert the values and their prediction value into a database
                model_insert.save()

                # Alter probability of default into front-end format.
                loan_default_prob = str(round(loan_default_prob[0]*100,4))+"%"
                # To ensure values are of adequate type and clean.
                # successful_model_post is 0 until reaching this point, then is altered to 1. This is utilized by javascript on the frontend.
                successful_model_post = 1
                return render(request, 'credit_model/thanks.html',{'prediction_value':loan_default_prob,
                                                                   'successful_model_post':successful_model_post,
                                                                   'City':City,
                                                                   'State':State,
                                                                   'BankState':BankState,
                                                                   'Term':Term,
                                                                   'NumberEmp':NumberEmp,
                                                                   'NewExist':NewExist,
                                                                   'UrbanRural':UrbanRural,
                                                                   'DisbursementGross':DisbursementGross})
            else:
                form = LoanForm()
                # To ensure values are of adequate type and clean.
                # successful_model_post is 0 until reaching this point, then is altered to 1. This is utilized by javascript on the frontend.
                successful_model_post = 0
                return render(request, 'credit_model/model_index.html',
                                        {'form': form,'invalid_model_input':'Invalid Model Input',
                                        'successful_model_post':successful_model_post})
        else:
            form = LoanForm()
            return render(request, 'credit_model/model_index.html', {'form': form})



def load_cities(request):
    state_id = request.GET.get('state')
    cities = City.objects.filter(state_id=state_id).order_by('name')
    return render(request, 'credit_model/city_dropdown_list_options.html', {'cities': cities})

templates/credit_model/about.html
{% extends 'credit_model/base.html' %}
{% block body_block %}

<center>
<h2>About the Project</h2>
</center>
<hr>

<h3 style='font-weight:bold;'>
  What is Credit Risk Modeling?
</h3>

  <br><br>

<h4  style='line-height: 1.6;'>
  Put simply, credit risk modeling relates to the task of predicting whether a loan will default based on the variables related to the loan itself.
  Such a task is rather important in the finance industry, due to the capital at risk in the loan.
  Over the last few decades, the utilization of data science and algorithms to predict a loan recipient's outcome have become immensely relevent.
  Data science approaches allow banks to utilize unbiased methods to approve, and not approve, of potential loans based on what the models probabilistically display.
  If you're interested in knowing more about credit risk modeling, <a href="https://www.heroku.com" target="_blank">here is a more extensive discussion</a>
  on what credit risk modeling really is.
</h4>
<br>
<h3 style='font-weight:bold;'>
   What's under the hood?
</h3>
<br><br>

<h4  style='line-height: 1.6;'>
    What you interact with here is a pre-trained model placed into production utilizing
    <a href="https://www.heroku.com" target="_blank"> Heroku</a> and the <a href="https://www.djangoproject.com" target="_blank">python web-framework, Django</a>.
    Through the utilization of these tools, we have been able to deploy a random forest classification model based on data provided by Dr. Brent Albrecht.
    Our model was iteratively trained through an extensive process which resulted in our choice of the variables you see on the
    <a href="{% url 'credit_model:model_input' %}">model</a> page. Our model works to utilze your input, make a probability prodiction of default, and returns it to you.
    While our model is trained and ready to use, we are not ourselves qualified to deliver loan adequacy advise from this model alone, due to our limited data pool.
    In turn, we also do not lay claim to any of the loan outcomes you see from this model. <span style ='color:#BE1E2D'>Use at your own risk</span>. We would also like to reiterate,
    that this dataset is based in the past and most likely does not reflect current loan environments.
</h4>
{% endblock %}

templates/credit_model/base.html
{% load static %}
{% load compress %}
<!DOCTYPE html>
<html lang="en">
<head>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-155055795-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-155055795-3');
</script>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://use.typekit.net/yld2snq.css">
<script src="https://kit.fontawesome.com/0d75512ab8.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

  <title>Credit Risk Modeling</title>

  {% compress css %}
  <link rel="stylesheet" href="{% static 'css/main.scss'%}" type="text/x-scss"/>
  {% endcompress %}
</head>
<body>
 <div id='holder'>
   <div class="container">
      <a href="http://www.inferencearchitects.com" style='text-align:center;' class='logo'>
        <img src="{% static 'IA_Logo.png'%}" alt="aw shucks">
      </a>
   </div>
   <br>
  <div class="container" style='background-color:#474747;'>
  <header>
    <div class="nav-container">
      <nav class="navbar navbar-expand-md">
        <a href="/">
          <h4 style='color:#1B9591'>Credit Risk Modeling</h4>
        </a>
            <button class="navbar-toggler"
                    data-target="#navbarSupportedContent"
                    data-toggle="collapse">
                    <span class="line"></span>
                    <span class="line"></span>
            </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <br>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class='nav-link' href="/"><h4>Home</h4></a>
              </li>
              <li class="nav-item">
                <a class='nav-link' href="{% url 'credit_model:about' %}"><h4>Description</h4></a>
              </li>
              <li class="nav-item">
                <a class='nav-link' href="{% url 'credit_model:fed_data' %}"><h4>Federal Reserve Data</h4></a>
              </li>
              <li class="nav-item">
                <a class='nav-link' href="{% url 'credit_model:model_input' %}"><h4>Model</h4></a>
              </li>
            </ul>
          </div>
      </nav>
      </div>
    </header>
    <br>
    <div id='body' style='padding-top:2%;'>
      {% block body_block %}
      {% endblock %}
    </div>
    <br>
    <div class="row" style='padding-top:3%;background-color:#000;padding-bottom:2%;position:relative;'>
          <div class="col-sm-6" id='footer_cols'>
            <p>Contact: +1-801-641-6834</p>
          </div>
          <div class="col-sm-6" id='footer_cols'>
            <a href="mailto:ckinkadedarling@gmail.com" target="_blank">
              <p>Send us a message!</p>
            </a>
          </div>
          <h6 class = 'col-sm-12'style="color:#474747;text-align:center;" id='footer_disclaimer'> &copy; 2020 | Inference Architects, LLC | All Rights Reserved</h6>
        </div>
    </div>
  </div>
</body>
</html>

templates/credit_model/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

templates/credit_model/fed_data.html
{% extends 'credit_model/base.html' %}
{% load django_tables2 %}
{% load bootstrap3 %}
{% block body_block %}
<div class="container">

<h1 style='text-align:center;'>
  Federal Reserve 'Charge-Off' Rates 1985 - 2019
</h1>
<hr>
<h5>
  What you are seeing here is data provided by the Federal Reserve. You can access the source of this data <a href="https://www.federalreserve.gov/releases/chargeoff/chgallnsa.htm">here</a>.
  The values on this page are non-seasonally adjusted 'Charge-Off' rates of business loans. A 'Charge-off' is another term for 'default'. The values presented here as 'DefaultRate' are the
  percentage of defaults in loans in the United States. These values are accompanied by 'Year' and 'Quarter' values to allow for data filtering.
  This data is important to have alongside the loan classifcation model for two reasons:
  <br><br>
   <ol>
     <li>It is important to have a benchmark to compare potential loans to. This is especially the case when the tool on display here provides loan default probabilities.
     While probabilites provide some understanding of the risk associated with a loan, it is also essential to understand where the nation is sitting overall in terms of default.
     Knowing the overall 'health' of business loans allows a loan originator to better understand the risk premium attached to any loan. </li>
  <br>
     <li>This data is gathered by a governing financial instituation. What we are able to understand is that these numbers are to be trusted and extrapolated upon.</li>
   </ol>
</h5>
{% if filter %}
<!-- <span id='only_for_scroll'></span> -->
<div class="filter_row list_filter_row row marl"id='only_for_scroll'>
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <form id="fed_filter" method="GET" action="{% url 'credit_model:fed_data' %}#fed_filter">
          {% csrf_token %}
          <div class="card-body">
            <div class="card-title" style='text-align:center;'>Filters</div>
            <div class="row marl justify-content-center">
                  {% bootstrap_form filter.form %}
                <div class="filter_col text-left col-sm-3">
                  <br>
                  <div class="form-group buttons_row">
                    <button class="btn btn-primary save" type="submit" id='filter_btn'>Filter</button>
                    <a href="{% url 'credit_model:fed_data' %}" class="btn btn-primary save">Clear</a>
                    </div>
                  </div>
                </div>
              </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endif %}
<div class="table_container_row row marl" id='DataTable'>
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="panel-heading-list card-title text-right">
          <span class="filter_toggle" id='filter_toggle'>
            <a href="#" class="primary_btn"><i class="fas fa-filter"></i></a>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>
{% render_table table "credit_model/table.html" %}

</div>
{% block js_block %}
<script type="text/javascript">
  $(document).ready(function () {
    $("#filter_toggle").click(function () {
      $(".list_filter_row").toggle();
      $("html, body").animate({ scrollTop: $("#only_for_scroll").offset().top }, 1500);
      localStorage.setItem('my-scroll-pos', $(window).scrollTop());
        });
      });

      var pos = localStorage.getItem('my-scroll-pos', 0);
      if (pos){
        $(window).scrollTop(pos)
        delete pos
      };
  search = "{{ search }}"
  if (search == 'True') {
    $(".list_filter_row").close();
  };

  $("a[rel='page']").click(function (e) {
    e.preventDefault();
    $('#fed_filter').attr("action", $(this).attr("href"));
    $('#fed_filter').submit();
  });
</script>
{% endblock js_block %}

{% endblock %}

templates/credit_model/landing_index.html
{% extends 'credit_model/base.html' %}
{% block body_block %}
<h3 style='text-align:center;padding-bottom:20px;'>
  What is an Inference Architect?
</h3>
      <h4 style='text-align:center;font-weight:bold;'>
        We provide cost efficient data science and software development.
      </h4>
    <br><br>
      <h4  style='line-height: 1.6;'>
          An inference architect offers two arenas of expertise.
          They develop the systems you need to better manage your data, optimize your workflows, and create user friendly interfaces to better gather your data.
          Then, they go beyond the traditional development lifecycle to grow the business you are currently seeing by applying statistical inference and machine learning methods
          to the data you have on hand.
       </h4>
       <h4  style='line-height: 1.6;'>
           We partner with small to mid-sized organizations who see the need for software development and data science, but find it hard to stomach the immense cost.
           Our hope is that we can provide you with these business necessities at below market value for the full-time data science or software development team.
           Feel like we might be a good fit for the challenges you're facing? <a href="mailto: ckinkadedarling@gmail.com" target="_blank">Send us a message</a> and we will get back to you in a timely manner.

        </h4>
{% endblock %}

templates/credit_model/model_index.html
{% extends 'credit_model/base.html' %}
{% load bootstrap4 %}
{% block body_block %}
<div class="container">
<h1>Loan Information</h1>
<hr>
<h5>
  <span style='color:#BE1E2D'> Disclaimer: </span>
  This model was developed utilizing a small sample set. The results of this model are limited to the insights derived from the data
  on hand and may not reflect true outcomes.
</h5>
<br>
<p>
  Please fill out this form to the best of your ability. This information is essential for the model to return an adequate prediction.
 </p>

<form method="post" action="" id='ModelForm' data-cities-url="{% url 'credit_model:ajax_load_cities' %}" novalidate >
{% csrf_token %}
<div class="row">
  <div class="col-sm-6">
    <br>
    <label>Loan Term Length in Months (Max 360 Months):</label>
    <br>
    {{form.term}}
  </div>
  <div class="col-sm-6">
    <br>
    <label>Loan Amount (Max 3,600,000):</label>
    <br>
    {{form.disbursement_gross}}
  </div>
</div>
<div class="row">
  <div class="col-sm-6">
    <br>
    <label>Urban or Rural Business Location:</label>
    <br>
    {{form.urban_rural}}
  </div>
  <div class="col-sm-6">
    <br>
    <label>New Company or Existing Company:</label>
    <br>
    {{form.new_exist}}
  </div>
</div>
<div class="row">
  <div class="col-sm-6">
    <br>
    <label>State of Loan Recipient:</label>
    <br>
    {{form.state}}
  </div>
  <div class="col-sm-6">
    <br>
    <label>City of Loan Recipient:</label>
    <br>
    {{form.city}}
  </div>
</div>
<div class="row">
  <div class="col-sm-6">
    <br>
    <label>Number of Employees:</label>
    <br>
    {{form.number_emp}}
  </div>
  <div class="col-sm-6">
    <br>
    <label>Loan Issuer State:</label>
    <br>
    {{form.bank_state}}
  </div>
</div>
<br>
<input type="submit"value="Submit" class="button">

</form>
<br>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

{% if successful_model_post == 0 %}
<script>
  alert('{{ invalid_model_input }}');
</script>
{% endif %}

<script>
  $("#id_state").change(function () {
    var url = $("#ModelForm").attr("data-cities-url");  // get the url of the `load_cities` view
    var stateId = $(this).val();  // get the selected country ID from the HTML input

    $.ajax({                       // initialize an AJAX request
      url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
      data: {
        'state': stateId       // add the country id to the GET parameters
      },
      success: function (data) {   // `data` is the return of the `load_cities` view function
        $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
      }
    });

  });



</script>
{% endblock %}

templates/credit_model/thanks.html
{% extends 'credit_model/base.html' %}
{% block body_block %}
<div class="container">


<h1 style='text-align:center;'>
  Thank You!
</h1>
<hr>
<center>
  <br>
  <h4>Your Loan's Probability of Default</h4>
  <br>
  <h5 style='color:#1B9591'>{{ prediction_value }}</h5>
</center>
<br>
<div class="row">
  <div class="col-sm-6">
    <br>
    <h5>Loan Term Length in Months (Max 360 Months):</h5>
    <br>
    <span style='color:#1B9591'>{{Term}}</span>
  </div>
  <div class="col-sm-6">
    <br>
    <h5>Loan Amount (Max 3,600,000):</h5>
    <br>
    <span style='color:#1B9591;'>{{DisbursementGross}}</span>
  </div>
</div>
<div class="row">
  <div class="col-sm-6">
    <br>
    <h5>Urban or Rural Business Location:</h5>
    <br>
<span style='color:#1B9591'> {{UrbanRural}}</span>
  </div>
  <div class="col-sm-6">
    <br>
    <h5>New Company or Existing Company:</h5>
    <br>
  <span style='color:#1B9591'>{{NewExist}}</span>
  </div>
</div>
<br><br>
<div class="row">
  <div class="col-sm-6">
    <br>
    <h5>State of Loan Recipient:</h5>
    <br>
    <span style='color:#1B9591'> {{State}}</span>
  </div>
  <div class="col-sm-6">
    <br>
    <h5>City of Loan Recipient:</h5>
    <br>
    <span style='color:#1B9591'> {{City}}</span>
  </div>
</div>
<br><br>
<div class="row">
  <div class="col-sm-6">
    <br>
    <h5>Number of Employees:</h5>
    <br>
  <span style='color:#1B9591'>  {{NumberEmp}}</span>
  </div>
  <div class="col-sm-6">
    <br>
    <h5>Loan Issuer State:</h5>
    <br>
  <span style='color:#1B9591'>  {{BankState}}</span>
  </div>
</div>
<br><br>
<hr>
<br>
</div>
{% endblock %}